package ui.MaintenanceTeam;

import business.Business;
import business.EmailAlert.EmailAlert;
import business.Enterprise.MaintenanceTeamEnterprise;
import business.Role.ResidentRole;
import business.Role.Role;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class GeneralMaintainenceWorkArea extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    MaintenanceTeamEnterprise par;
    Business business;

    public GeneralMaintainenceWorkArea(JPanel userProcessContainer, UserAccount account, MaintenanceTeamEnterprise par, Business business) {

        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.par = par;
        this.business = business;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAssigned = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnCloseRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        tblRequests.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unit No.", "Resident Name", "Assigned", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequests);

        btnRefresh.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAssignToMe.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAssignToMe.setText("Assign to me");
        btnAssignToMe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Assignment To Me");

        tblAssigned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unit No.", "Resident Name", "Assigned", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAssigned);

        btnProcess.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnProcess.setText("Process My Job");
        btnProcess.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnCloseRequest.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCloseRequest.setText("Close Request");
        btnCloseRequest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCloseRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseRequestActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("General Maintainence Job Work Portal");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCloseRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(341, 341, 341))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(603, 603, 603))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateme();
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        // Get selected row in tblRequests
        int selectedRow = tblRequests.getSelectedRow();

        // If a row is selected
        if (selectedRow >= 0) {
            // Get the work request from the selected row
            WorkRequest request = (WorkRequest) tblRequests.getValueAt(selectedRow, 0);

            // Check if the request is already completed
            if (request.getMessage().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");
                return;
            } else {
                // Set the receiver as the current user and update the status
                request.setReceiver(account);
                request.setStatus("Assigned");

                // Add the request to the user's work queue
                account.getWorkQueue().getWorkRequestList().add(request);

                // Remove the request from the original work queue
                par.getWorkQueue().getWorkRequestList().remove(request);

                // Show success message
                JOptionPane.showMessageDialog(null, "Service Request Assigned");

                // Refresh both tables
                populateTable(); // Refresh tblRequests
                populateme();    // Refresh tblAssigned
            }
        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to process.");
        }
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // Get the selected row in tblAssigned
        int selectedRow = tblAssigned.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the work request from the selected row in tblAssigned
            WorkRequest request = (WorkRequest) tblAssigned.getValueAt(selectedRow, 0);

            // Validate that the request is not null
            if (request != null) {
                // Prompt the user for a message using an input dialog
                String message = JOptionPane.showInputDialog(this, "Enter a message for the request:", "Process Job", JOptionPane.PLAIN_MESSAGE);

                // Check if the user provided a message
                if (message != null && !message.trim().isEmpty()) {
                    // Update the request status and message
                    request.setStatus("In Progress");
                    request.setMessage(message.trim()); // Trim any leading/trailing spaces

                    // Show a success message
                    JOptionPane.showMessageDialog(this, "Service Request updated to 'In Progress' with message: " + message);

                    // Update the status in the original work queue (if necessary)
                    for (WorkRequest wr : par.getWorkQueue().getWorkRequestList()) {
                        if (wr.equals(request)) {
                            wr.setStatus("In Progress");
                            break;
                        }
                    }

                    // Refresh the table to reflect changes
                    populateme();  // Refresh tblAssigned
                } else {
                    // Show an error message if the user did not provide a message
                    JOptionPane.showMessageDialog(this, "Message cannot be empty. Please try again.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid request selected.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Choose a request to process.");
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnCloseRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseRequestActionPerformed
        // Get the selected row in tblAssigned
        int selectedRow = tblAssigned.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the selected WorkRequest
            WorkRequest request = (WorkRequest) tblAssigned.getValueAt(selectedRow, 0);

            // Mark the request as "Closed"
            request.setStatus("Closed");

            // Remove the request from the user's assigned work queue
            account.getWorkQueue().getWorkRequestList().remove(request);

            // Update the original work queue to reflect the closed status
            for (WorkRequest wr : par.getWorkQueue().getWorkRequestList()) {
                if (wr.equals(request)) {
                    wr.setStatus("Closed");
                    break;
                }
            }

            JOptionPane.showMessageDialog(null, "Service Request Closed");

            // Ensure the sender is a valid UserAccount
            if (request.getSender() instanceof UserAccount) {
                UserAccount sender = (UserAccount) request.getSender();

                // Check if the sender has a ResidentRole and ensure their email is not null
                if (sender.getRole() instanceof ResidentRole) {
                    ResidentRole residentRole = (ResidentRole) sender.getRole();
                    if (sender.getEmail() != null && !sender.getEmail().isEmpty()) {
                        String facility = request.getMessage();  // Assuming the facility info is in the message
                        EmailAlert emailAlert = new EmailAlert();
                        emailAlert.sendMaintenanceRequestClosedEmail(residentRole, facility);
                    } else {
                        System.out.println("No email found for the resident. Skipping email notification.");
                    }
                }
            }

            // Refresh both tables
            populateTable();  // Refresh tblRequests
            populateme();     // Refresh tblAssigned
        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to close.");
        }
    }//GEN-LAST:event_btnCloseRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnCloseRequest;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAssigned;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
        model.setRowCount(0);

        for (WorkRequest request : par.getWorkQueue().getWorkRequestList()) {
            if ("General Maintenance".equalsIgnoreCase(request.getType())) {
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = request.getSender().id;
                row[2] = request.getReceiver() == null ? null : request.getReceiver().getUsername();
                row[3] = request.getStatus();
                row[4] = request.getMessage();
                model.addRow(row);
            }
        }
    }

    public void populateme() {
        DefaultTableModel model = (DefaultTableModel) tblAssigned.getModel();
        model.setRowCount(0);

        for (WorkRequest workl : account.getWorkQueue().getWorkRequestList()) {
            if ("General Maintenance".equalsIgnoreCase(workl.getType())) {
                Object[] row = new Object[5];
                row[0] = workl;
                row[1] = workl.getSender().id;
                row[2] = workl.getReceiver() == null ? null : workl.getReceiver().getUsername();
                row[3] = workl.getStatus();
                row[4] = workl.getMessage();
                model.addRow(row);
            }
        }
    }
}
