package ui.AdministrativeRole;

import business.Business;
import business.Enterprise.Enterprise;
import business.Enterprise.MaintenanceTeamEnterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.Analytics.MaintenanceAnalyticsJPanel;

public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;

    public AdminWorkAreaJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        analyticsJPanel = new javax.swing.JButton();
        btnMaintenanceAnalytics = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        userJButton.setBackground(new java.awt.Color(153, 204, 255));
        userJButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        userJButton.setText("Manage Users");
        userJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });

        manageEmployeeJButton.setBackground(new java.awt.Color(255, 255, 102));
        manageEmployeeJButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        manageEmployeeJButton.setText("Manage Organisation");
        manageEmployeeJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });

        manageOrganizationJButton.setBackground(new java.awt.Color(255, 51, 51));
        manageOrganizationJButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        manageOrganizationJButton.setText("Manage Enterprises");
        manageOrganizationJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADMINISTRATIVE WORK AREA");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        analyticsJPanel.setBackground(new java.awt.Color(102, 255, 102));
        analyticsJPanel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        analyticsJPanel.setText("Residents Analytics");
        analyticsJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analyticsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticsJPanelActionPerformed(evt);
            }
        });

        btnMaintenanceAnalytics.setBackground(new java.awt.Color(255, 102, 204));
        btnMaintenanceAnalytics.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnMaintenanceAnalytics.setText("Maintenance Service Req Graph");
        btnMaintenanceAnalytics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMaintenanceAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceAnalyticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(analyticsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaintenanceAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(analyticsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(btnMaintenanceAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(146, 146, 146))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, business);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageOrganisationJPanel manageEmployeeJPanel = new ManageOrganisationJPanel(userProcessContainer, business.getEnterpriseDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageEnterpriseJPanel manageOrganizationJPanel = new ManageEnterpriseJPanel(userProcessContainer, business.getEnterpriseDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void analyticsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsJPanelActionPerformed
        // TODO add your handling code here:
        AnalyticsJPanel analyticsJPanel = new AnalyticsJPanel(userProcessContainer, business.getEnterpriseDirectory());
        userProcessContainer.add("analyticsJPanel", analyticsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_analyticsJPanelActionPerformed

    private void btnMaintenanceAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceAnalyticsActionPerformed
        // Find the MaintenanceTeamEnterprise from the business enterprise directory
        MaintenanceTeamEnterprise maintenanceEnterprise = null;
        for (Enterprise enterprise : business.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof MaintenanceTeamEnterprise) {
                maintenanceEnterprise = (MaintenanceTeamEnterprise) enterprise;
                break;
            }
        }

        // Check if we have found the MaintenanceTeamEnterprise
        if (maintenanceEnterprise != null) {
            // Create an instance of MaintenanceAnalyticsJPanel and pass the enterprise data
            MaintenanceAnalyticsJPanel analyticsPanel = new MaintenanceAnalyticsJPanel(userProcessContainer, maintenanceEnterprise);

            // Add the MaintenanceAnalyticsJPanel to the userProcessContainer
            userProcessContainer.add("MaintenanceAnalyticsJPanel", analyticsPanel); // Add the new panel to the container

            // Use CardLayout to switch to the new panel
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.show(userProcessContainer, "MaintenanceAnalyticsJPanel");
        } else {
            // Show an error if the Maintenance Team Enterprise is not found
            JOptionPane.showMessageDialog(this, "Maintenance Team Enterprise not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnMaintenanceAnalyticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyticsJPanel;
    private javax.swing.JButton btnMaintenanceAnalytics;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables

}
