package ui.PestControlTeam;

import business.Business;
import business.EmailAlert.EmailAlert;
import business.Enterprise.Enterprise;
import business.Enterprise.PestControlEnterprise;
import business.Role.ResidentRole;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class MicrobialTeamWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    private UserAccount userAccount;
    private PestControlEnterprise pestOrganization;

    public MicrobialTeamWorkArea(JPanel userProcessContainer, UserAccount account, Enterprise organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.pestOrganization = (PestControlEnterprise) organization;

        System.out.println(pestOrganization.getName());

        populate();
    }

    public void populate() {
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();

        model.setRowCount(0);

        for (WorkRequest request : pestOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender().id;
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getOrganisation().getName();
            row[3] = request.getStatus();
            row[4] = request.getMessage();

            model.addRow(row);
        }
    }

    public void populateme() {
        DefaultTableModel model = (DefaultTableModel) Assigned.getModel();

        model.setRowCount(0);

        for (WorkRequest workl : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = workl;
            row[1] = workl.getSender().id;
            row[2] = workl.getReceiver() == null ? null : workl.getReceiver().getUsername();
            row[3] = workl.getStatus();
            row[4] = workl.getMessage();

            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Assigned = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnCloseRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Microbial Team Job Work Portal");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 6, 698, 54));

        tblRequests.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unit No.", "Resident Name", "Assigned", "Status", "Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 102, 698, 237));

        btnRefresh.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 130, 40));

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton2.setText("Assign to me");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 377, 153, 37));

        Assigned.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Assigned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unit No.", "Resident Name", "Assigned", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Assigned);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 450, 698, 231));

        btnProcess.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnProcess.setText("Process My Job");
        btnProcess.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 699, 153, 37));

        btnCloseRequest.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCloseRequest.setText("Close Request");
        btnCloseRequest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCloseRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseRequestActionPerformed(evt);
            }
        });
        add(btnCloseRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 699, 153, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Images/Deliverywork.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 830));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateme();
        populate();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Get selected row in tblRequests
        int selectedRow = tblRequests.getSelectedRow();

        // If a row is selected
        if (selectedRow >= 0) {
            // Get the work request from the selected row
            WorkRequest request = (WorkRequest) tblRequests.getValueAt(selectedRow, 0);

            // Check if the request is already completed
            if (request.getMessage().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");
                return;
            } else {
                // Set the receiver as the current user and update the status
                request.setReceiver(userAccount);
                request.setStatus("Assigned");

                // Add the request to the user's work queue
                userAccount.getWorkQueue().getWorkRequestList().add(request);

                // Remove the request from the original work queue
                pestOrganization.getWorkQueue().getWorkRequestList().remove(request);

                // Show success message
                JOptionPane.showMessageDialog(null, "Service Request Assigned");

                // Refresh both tables
                populate(); // Refresh tblRequests
                populateme();    // Refresh tblAssigned
            }
        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to process.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // Get the selected row in tblAssigned
        int selectedRow = Assigned.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the work request from the selected row in tblAssigned
            WorkRequest request = (WorkRequest) Assigned.getValueAt(selectedRow, 0);

            // Validate that the request is not null
            if (request != null) {
                // Prompt the user for a message using an input dialog
                String message = JOptionPane.showInputDialog(this, "Enter a message for the request:", "Process Job", JOptionPane.PLAIN_MESSAGE);

                // Check if the user provided a message
                if (message != null && !message.trim().isEmpty()) {
                    // Update the request status and message
                    request.setStatus("In Progress");
                    request.setMessage(message.trim()); // Trim any leading/trailing spaces

                    // Show a success message
                    JOptionPane.showMessageDialog(this, "Service Request updated to 'In Progress' with message: " + message);

                    // Update the status in the original work queue (if necessary)
                    for (WorkRequest wr : pestOrganization.getWorkQueue().getWorkRequestList()) {
                        if (wr.equals(request)) {
                            wr.setStatus("In Progress");
                            break;
                        }
                    }

                    // Refresh the table to reflect changes
                    populateme();  // Refresh tblAssigned
                } else {
                    // Show an error message if the user did not provide a message
                    JOptionPane.showMessageDialog(this, "Message cannot be empty. Please try again.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid request selected.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Choose a request to process.");
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnCloseRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseRequestActionPerformed
        // Get the selected row in tblAssigned
        int selectedRow = Assigned.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the selected WorkRequest
            WorkRequest request = (WorkRequest) Assigned.getValueAt(selectedRow, 0);

            // Mark the request as "Closed"
            request.setStatus("Closed");

            // Remove the request from the user's assigned work queue
            userAccount.getWorkQueue().getWorkRequestList().remove(request);

            // Update the original work queue to reflect the closed status
            for (WorkRequest wr : pestOrganization.getWorkQueue().getWorkRequestList()) {
                if (wr.equals(request)) {
                    wr.setStatus("Closed");
                    break;
                }
            }

            JOptionPane.showMessageDialog(null, "Service Request Closed");

            // Ensure the sender is a valid UserAccount
            if (request.getSender() instanceof UserAccount) {
                UserAccount sender = (UserAccount) request.getSender();

                // Check if the sender has a ResidentRole and ensure their email is not null
                if (sender.getRole() instanceof ResidentRole) {
                    ResidentRole residentRole = (ResidentRole) sender.getRole();
                    if (sender.getEmail() != null && !sender.getEmail().isEmpty()) {
                        String facility = request.getMessage();  // Assuming the facility info is in the message
                        EmailAlert emailAlert = new EmailAlert();
                        emailAlert.sendMaintenanceRequestClosedEmail(residentRole, facility);
                    } else {
                        System.out.println("No email found for the resident. Skipping email notification.");
                    }
                }
            }

            // Refresh both tables
            populate();  // Refresh tblRequests
            populateme();     // Refresh tblAssigned
        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to close.");
        }
    }//GEN-LAST:event_btnCloseRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Assigned;
    private javax.swing.JButton btnCloseRequest;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables
}
